// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Refreshtk struct {
	ID     int64
	Userid int64
	Token  string
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	Isactive     sql.NullBool
	Role         string
}
