// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Refreshtk struct {
	ID     int32
	Userid int32
	Token  string
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	Isactive     pgtype.Bool
	Role         string
}
