// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const cleanRefreshToken = `-- name: CleanRefreshToken :exec
DELETE FROM refreshtk
WHERE userid = (SELECT id FROM users WHERE username = $1)
`

func (q *Queries) CleanRefreshToken(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, cleanRefreshToken, username)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refreshtk (userid, token) VALUES ($1, $2)
RETURNING id, userid, token
`

type CreateRefreshTokenParams struct {
	Userid int32
	Token  string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (Refreshtk, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.Userid, arg.Token)
	var i Refreshtk
	err := row.Scan(&i.ID, &i.Userid, &i.Token)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, isactive, role FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Isactive,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, isactive, role FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Isactive,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, created_at, isactive, role FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Isactive,
		&i.Role,
	)
	return i, err
}

const login = `-- name: Login :one
SELECT id, username, email, password_hash, created_at, isactive, role FROM users WHERE username = $1 AND password_hash = $2
`

type LoginParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (User, error) {
	row := q.db.QueryRow(ctx, login, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Isactive,
		&i.Role,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           int32
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1 OR email = $2) AS user_exists
`

type UserExistsParams struct {
	Username string
	Email    string
}

func (q *Queries) UserExists(ctx context.Context, arg UserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, arg.Username, arg.Email)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const validRefreshToken = `-- name: ValidRefreshToken :one
SELECT u.username, u.role
FROM users u
JOIN refreshtk r ON r.userid = u.id
WHERE r.token = $1 AND u.isactive = TRUE
LIMIT 1
`

type ValidRefreshTokenRow struct {
	Username string
	Role     string
}

func (q *Queries) ValidRefreshToken(ctx context.Context, token string) (ValidRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, validRefreshToken, token)
	var i ValidRefreshTokenRow
	err := row.Scan(&i.Username, &i.Role)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users
SET isactive = TRUE
WHERE id = $1 AND isactive = FALSE
RETURNING id, username, email, password_hash, created_at, isactive, role
`

func (q *Queries) VerifyUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, verifyUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Isactive,
		&i.Role,
	)
	return i, err
}
